// frontend/src/farm/Farms.tsx
import React, {useEffect} from 'react'
import {Box, Button, Chip, Tooltip, Typography,} from '@mui/material'
import {DataGrid, GridActionsCellItem, GridColDef, GridToolbar,} from '@mui/x-data-grid'
import {Add as AddIcon, Delete as DeleteIcon, Edit as EditIcon, Note as NoteIcon,} from '@mui/icons-material'
import {useNavigate, useParams} from 'react-router-dom'
import {type Contact, FarmStoreProvider, useFarmStore, type FarmWithContacts} from '@/stores/farmStore'
import {withApiClient, type ApiClient} from '@/api/client'
import LocationPopover from './LocationPopover'
import NotesDrawer from './NotesDrawer'
import FarmCreateEditDialog from './FarmCreateEditDialog'
import FarmDeleteDialog from './FarmDeleteDialog'

interface FarmsProps {
    apiClient: ApiClient
}

// Inner component that uses the store
const FarmsContent: React.FC = () => {
    const navigate = useNavigate()
    const {organization = 'default'} = useParams()
    const {
        table,
        getAll,
        createEditShow,
        showNotes,
        removeShow,
        updateTableOptions,
    } = useFarmStore()

    useEffect(() => {
        getAll()
    }, [getAll])

    const getContactRoleColor = (role: string): 'success' | 'info' | 'warning' | 'default' => {
        switch (role?.toLowerCase()) {
            case 'owner':
                return 'success'
            case 'worker':
                return 'info'
            case 'advisor':
                return 'warning'
            default:
                return 'default'
        }
    }

    const navigateToContact = (contactId: string) => {
        navigate(`/${organization}/contacts`, {
            state: {contact_id: contactId}
        })
    }

    const handleShowNotes = (farm: FarmWithContacts) => {
        showNotes(farm)
    }

    const handleEdit = (farm: FarmWithContacts) => {
        createEditShow(farm)
    }

    const handleDelete = (farm: FarmWithContacts) => {
        removeShow(farm)
    }

    const columns: GridColDef[] = [
        {
            field: 'farm_name',
            headerName: 'Farm Name',
            width: 250,
            renderCell: (params) => (
                <Typography variant="body2" fontWeight="medium">
                    {params.value}
                </Typography>
            ),
        },
        {
            field: 'location',
            headerName: 'Location',
            width: 200,
            sortable: false,
            renderCell: (params) => {
                if (params.value) {
                    return (
                        <LocationPopover
                            location={params.value}
                            farmName={params.row.farm_name}
                        />
                    )
                }
                return (
                    <Typography variant="body2" color="text.secondary">
                        No location
                    </Typography>
                )
            },
        },
        {
            field: 'contacts',
            headerName: 'Contacts',
            width: 400,
            sortable: false,
            renderCell: (params) => {
                const contacts = params.value as Contact[]
                if (contacts && contacts.length > 0) {
                    return (
                        <Box sx={{display: 'flex', flexWrap: 'wrap', gap: 0.5}}>
                            {contacts.map((contact) => (
                                <Chip
                                    key={contact.id}
                                    label={contact.name}
                                    size="small"
                                    color={getContactRoleColor(contact.role)}
                                    onClick={() => navigateToContact(contact.id)}
                                    sx={{cursor: 'pointer', margin: 0.25}}
                                />
                            ))}
                        </Box>
                    )
                }
                return (
                    <Typography variant="body2" color="text.secondary">
                        No contacts
                    </Typography>
                )
            },
        },
        {
            field: 'actions',
            type: 'actions',
            headerName: '',
            width: 150,
            getActions: (params) => [
                <GridActionsCellItem
                    key="edit"
                    icon={
                        <Tooltip title="Edit Farm">
                            <EditIcon/>
                        </Tooltip>
                    }
                    label="Edit Farm"
                    onClick={() => handleEdit(params.row)}
                    color="primary"
                />,
                <GridActionsCellItem
                    key="notes"
                    icon={
                        <Tooltip title="View Notes">
                            <NoteIcon/>
                        </Tooltip>
                    }
                    label="View Notes"
                    onClick={() => handleShowNotes(params.row)}
                    color="primary"
                />,
                <GridActionsCellItem
                    key="delete"
                    icon={
                        <Tooltip title="Delete Farm">
                            <DeleteIcon/>
                        </Tooltip>
                    }
                    label="Delete Farm"
                    onClick={() => handleDelete(params.row)}
                    color="error"
                />,
            ],
        },
    ]

    const handlePaginationModelChange = (model: { page: number; pageSize: number }) => {
        updateTableOptions({
            page: model.page + 1, // DataGrid uses 0-based indexing
            itemsPerPage: model.pageSize,
        })
    }

    const handleSortModelChange = (model: readonly any[]) => {
        if (model.length > 0) {
            updateTableOptions({
                sortBy: [model[0].field],
                descending: [model[0].sort === 'desc'],
            })
        }
    }

    return (
        <Box sx={{ 
            p: 3, 
            backgroundColor: '#f8f9fa', 
            minHeight: '100%',
            width: '100%',
            maxWidth: 'none',
        }}>
            <NotesDrawer/>
            <FarmCreateEditDialog/>
            <FarmDeleteDialog/>

            {/* Header */}
            <Box sx={{ mb: 3, width: '100%' }}>
                <Box sx={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', mb: 2 }}>
                    <Typography 
                        variant="h4" 
                        component="h1"
                        sx={{ 
                            fontWeight: 400,
                            fontSize: '28px',
                            color: '#3c4043',
                            fontFamily: '"Google Sans", Roboto, sans-serif',
                        }}
                    >
                        Farms
                    </Typography>
                    <Button
                        variant="contained"
                        startIcon={<AddIcon/>}
                        onClick={() => createEditShow()}
                        sx={{
                            backgroundColor: '#1976d2',
                            boxShadow: '0 1px 2px 0 rgba(60,64,67,0.3), 0 1px 3px 1px rgba(60,64,67,0.15)',
                            '&:hover': {
                                backgroundColor: '#1565c0',
                                boxShadow: '0 1px 3px 0 rgba(60,64,67,0.3), 0 4px 8px 3px rgba(60,64,67,0.15)',
                            },
                            textTransform: 'none',
                            fontWeight: 500,
                            fontSize: '14px',
                            borderRadius: '4px',
                            px: 3,
                            py: 1,
                        }}
                    >
                        CREATE FARM
                    </Button>
                </Box>
                <Typography 
                    variant="body2" 
                    sx={{ 
                        color: '#5f6368',
                        fontSize: '14px',
                        mb: 2,
                    }}
                >
                    Manage your farm resources and track agricultural operations
                </Typography>
            </Box>

            {/* Data Table */}
            <Box
                sx={{
                    backgroundColor: '#ffffff',
                    borderRadius: '8px',
                    boxShadow: '0 1px 2px 0 rgba(60,64,67,0.3), 0 1px 3px 1px rgba(60,64,67,0.15)',
                    overflow: 'hidden',
                    width: '100%',
                }}
            >
                <DataGrid
                    rows={table.rows.items}
                    columns={columns}
                    loading={table.loading}
                    pagination
                    paginationMode="server"
                    sortingMode="server"
                    rowCount={table.rows.total || 0}
                    paginationModel={{
                        page: table.options.page - 1, // DataGrid uses 0-based indexing
                        pageSize: table.options.itemsPerPage,
                    }}
                    onPaginationModelChange={handlePaginationModelChange}
                    onSortModelChange={handleSortModelChange}
                    pageSizeOptions={[10, 25, 50, 100]}
                    disableRowSelectionOnClick
                    slots={{
                        toolbar: GridToolbar,
                    }}
                    slotProps={{
                        toolbar: {
                            showQuickFilter: true,
                            quickFilterProps: {debounceMs: 500},
                        },
                    }}
                    onFilterModelChange={(model) => {
                        const quickFilterValue = model.quickFilterValues?.[0] || ''
                        updateTableOptions({q: quickFilterValue})
                    }}
                    sx={{
                        border: 'none',
                        '& .MuiDataGrid-main': {
                            '& .MuiDataGrid-columnHeaders': {
                                backgroundColor: '#f8f9fa',
                                borderBottom: '1px solid #e0e0e0',
                                fontSize: '14px',
                                fontWeight: 500,
                                color: '#3c4043',
                                '& .MuiDataGrid-columnHeaderTitle': {
                                    fontWeight: 500,
                                },
                            },
                            '& .MuiDataGrid-cell': {
                                borderBottom: '1px solid #f0f0f0',
                                fontSize: '14px',
                                color: '#3c4043',
                                display: 'flex',
                                alignItems: 'center',
                                '&:focus': {
                                    outline: 'none',
                                },
                            },
                            '& .MuiDataGrid-row': {
                                '&:hover': {
                                    backgroundColor: '#f8f9fa',
                                },
                                '&.Mui-selected': {
                                    backgroundColor: 'rgba(25, 118, 210, 0.08)',
                                    '&:hover': {
                                        backgroundColor: 'rgba(25, 118, 210, 0.12)',
                                    },
                                },
                            },
                        },
                        '& .MuiDataGrid-toolbarContainer': {
                            padding: '16px',
                            borderBottom: '1px solid #e0e0e0',
                            '& .MuiButton-root': {
                                color: '#5f6368',
                                fontSize: '14px',
                                textTransform: 'none',
                            },
                            '& .MuiInputBase-root': {
                                fontSize: '14px',
                            },
                        },
                        '& .MuiDataGrid-footerContainer': {
                            borderTop: '1px solid #e0e0e0',
                            backgroundColor: '#fafafa',
                            '& .MuiTablePagination-root': {
                                fontSize: '14px',
                                color: '#5f6368',
                            },
                        },
                        minHeight: 500,
                    }}
                />
            </Box>
        </Box>
    )
}

// Main component that provides the store
const Farms: React.FC<FarmsProps> = ({apiClient}) => {
    return (
        <FarmStoreProvider apiClient={apiClient}>
            <FarmsContent />
        </FarmStoreProvider>
    )
}

export default withApiClient(Farms)

// static/farmbase/src/farm/Farms.vue
<template>
  <v-container fluid>
    <notes-drawer/>
    <!--    <v-row no-gutters>-->
    <!--      <v-col>-->
    <!--        <v-alert closable icon="mdi-barn" prominent text type="info">-->
    <!--          Farms are agricultural properties managed by your organization. You can track farm details,-->
    <!--          contacts, and notes for each farm.-->
    <!--        </v-alert>-->
    <!--      </v-col>-->
    <!--    </v-row>-->
    <v-row align="center" justify="space-between" no-gutters>
      <!--      <v-col cols="8">-->
      <!--        <settings-breadcrumbs v-model="project" />-->
      <!--      </v-col>-->
      <v-col class="text-right">
        <v-btn color="info" class="ml-2" @click="createEditShow()"> New</v-btn>
      </v-col>
    </v-row>
    <v-row no-gutters>
      <v-col>
        <v-card variant="flat">
          <!--          <v-card-title>-->
          <!--            <v-text-field-->
          <!--              v-model="q"-->
          <!--              append-inner-icon="mdi-magnify"-->
          <!--              label="Search"-->
          <!--              single-line-->
          <!--              hide-details-->
          <!--              clearable-->
          <!--            />-->
          <!--          </v-card-title>-->
          <v-data-table-server
              :headers="headers"
              :items="items"
              :items-length="total || 0"
              v-model:page="page"
              v-model:items-per-page="itemsPerPage"
              v-model:sort-by="sortBy"
              v-model:sort-desc="descending"
              :loading="loading"
              loading-text="Loading... Please wait"
          >
            <template #item.farm_name="{ item }">
              <div class="font-weight-medium">{{ item.farm_name }}</div>
            </template>

            <template #item.location="{ item }">
              <location-popover
                  v-if="item.location"
                  :location="item.location"
                  :farm-name="item.farm_name"
              />
              <span v-else class="text-grey">No location</span>
            </template>

            <template #item.contacts="{ item }">
              <v-chip-group v-if="item.contacts && item.contacts.length > 0">
                <v-chip
                    v-for="contact in item.contacts"
                    :key="contact.id"
                    :color="getContactRoleColor(contact.role)"
                    size="small"
                    class="ma-1"
                    @click="navigateToContact(contact.id)"
                    style="cursor: pointer;"
                >
                  {{ contact.name }}
                </v-chip>
              </v-chip-group>
              <span v-else class="text-grey">No contacts</span>
            </template>

            <template #item.data-table-actions="{ item }">
              <div class="d-flex align-center">
                <v-tooltip location="top">
                  <template #activator="{ props }">
                    <v-btn
                        icon
                        variant="text"
                        color="primary"
                        size="small"
                        @click="showNotes(item)"
                        class="mr-2"
                        v-bind="props"
                    >
                      <v-icon>mdi-note</v-icon>
                    </v-btn>
                  </template>
                  <span>View Notes</span>
                </v-tooltip>
<!--                <raw-contact-viewer :value="item.raw"/>-->
              </div>

<!--              <v-menu location="right" origin="overlap">-->
<!--                <template #activator="{ props }">-->
<!--                  <v-btn icon variant="text" v-bind="props">-->
<!--                    <v-icon>mdi-dots-vertical</v-icon>-->
<!--                  </v-btn>-->
<!--                </template>-->
<!--                <v-list>-->
<!--                  <v-list-item @click="createEditShow(item)">-->
<!--                    <v-list-item-title>View / Edit</v-list-item-title>-->
<!--                  </v-list-item>-->
<!--                  <v-list-item @click="showNotes(item)">-->
<!--                    <v-list-item-title>Notes</v-list-item-title>-->
<!--                  </v-list-item>-->
<!--                </v-list>-->
<!--              </v-menu>-->
            </template>
          </v-data-table-server>
        </v-card>
      </v-col>
    </v-row>
  </v-container>
</template>

<script>
import {mapFields} from "vuex-map-fields"
import {mapActions} from "vuex"
import NotesDrawer from "./NotesDrawer.vue"
import LocationPopover from "./LocationPopover.vue"
import RawContactViewer from "@/contact/RawContactViewer.vue";

export default {
  name: "FarmsTable",
  components: {RawContactViewer, NotesDrawer, LocationPopover},
  props: {
    name: {
      type: String,
      default: null,
    },
  },
  data() {
    return {
      headers: [
        {title: "Farm Name", value: "farm_name", align: "left", width: "25%"},
        {title: "Location", value: "location", sortable: false, width: "20%"},
        {title: "Contacts", value: "contacts", sortable: false, width: "45%"},
        {title: "", key: "data-table-actions", sortable: false, align: "end", width: "10%"},
      ],
    }
  },
  computed: {
    ...mapFields("farm", [
      "table.loading",
      "table.options.descending",
      "table.options.filters.project",
      "table.options.itemsPerPage",
      "table.options.page",
      "table.options.q",
      "table.options.sortBy",
      "table.rows.items",
      "table.rows.total",
    ]),
    ...mapFields("auth", ["currentUser.projects"]),
  },
  methods: {
    ...mapActions("farm", ["getAll", "createEditShow", "removeShow", "showNotes"]),
    getContactRoleColor(role) {
      switch (role?.toLowerCase()) {
        case "owner":
          return "success"
        case "worker":
          return "info"
        case "advisor":
          return "warning"
        default:
          return "grey"
      }
    },
    navigateToContact(contactId) {
      this.$router.push({
        name: "ContactInstanceTable",
        params: {organization: this.$route.params.organization},
        query: {contact_id: contactId}
      })
    },
  },
  created() {
    this.project = [{name: this.$route.query.project}]
    this.getAll()

    this.$watch(
        (vm) => [vm.page],
        () => {
          this.getAll()
        }
    )

    this.$watch(
        (vm) => [vm.q, vm.itemsPerPage, vm.sortBy, vm.descending, vm.project],
        () => {
          this.page = 1
          this.$router.push({query: {project: this.project[0].name}})
          this.getAll()
        }
    )
  },
}
</script>
