// apps/farmbase/src/farmbase/static/farmbase_react/src/farm/LocationPopover.tsx
import React, { useState } from 'react'
import {
  Button,
  Card,
  CardContent,
  Typography,
  Box,
  Popover,
  IconButton,
} from '@mui/material'
import {
  LocationOn as LocationIcon,
  Map as MapIcon,
  OpenInNew as OpenInNewIcon,
  Close as CloseIcon,
} from '@mui/icons-material'

interface Location {
  latitude: number
  longitude: number
  address?: string
}

interface LocationPopoverProps {
  location: Location
  farmName: string
}

const LocationPopover: React.FC<LocationPopoverProps> = ({ location, farmName }) => {
  const [anchorEl, setAnchorEl] = useState<HTMLButtonElement | null>(null)

  const handleClick = (event: React.MouseEvent<HTMLButtonElement>) => {
    setAnchorEl(event.currentTarget)
  }

  const handleClose = () => {
    setAnchorEl(null)
  }

  const open = Boolean(anchorEl)

  const formatLocation = (loc: Location): string => {
    return `${loc.latitude.toFixed(4)}, ${loc.longitude.toFixed(4)}`
  }

  const getGoogleMapsLink = (): string => {
    return `https://www.google.com/maps?q=${location.latitude},${location.longitude}`
  }

  return (
    <>
      <Button
        variant="text"
        color="primary"
        size="small"
        startIcon={<LocationIcon />}
        onClick={handleClick}
        sx={{ textTransform: 'none' }}
      >
        {formatLocation(location)}
      </Button>

      <Popover
        open={open}
        anchorEl={anchorEl}
        onClose={handleClose}
        anchorOrigin={{
          vertical: 'bottom',
          horizontal: 'left',
        }}
        transformOrigin={{
          vertical: 'top',
          horizontal: 'left',
        }}
      >
        <Card sx={{ minWidth: 350, maxWidth: 400 }}>
          <CardContent>
            <Box sx={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', mb: 2 }}>
              <Typography variant="h6" component="div" sx={{ display: 'flex', alignItems: 'center', gap: 1 }}>
                <LocationIcon />
                {farmName} Location
              </Typography>
              <IconButton size="small" onClick={handleClose}>
                <CloseIcon />
              </IconButton>
            </Box>

            <Box sx={{ mb: 3 }}>
              <Typography variant="caption" color="text.secondary">
                Coordinates
              </Typography>
              <Typography variant="body2">
                <strong>Latitude:</strong> {location.latitude.toFixed(6)}<br />
                <strong>Longitude:</strong> {location.longitude.toFixed(6)}
              </Typography>
            </Box>

            {location.address && (
              <Box sx={{ mb: 3 }}>
                <Typography variant="caption" color="text.secondary">
                  Address
                </Typography>
                <Typography variant="body2">
                  {location.address}
                </Typography>
              </Box>
            )}

            {/* Map placeholder */}
            <Box
              sx={{
                height: 150,
                border: '1px solid',
                borderColor: 'divider',
                borderRadius: 1,
                display: 'flex',
                flexDirection: 'column',
                alignItems: 'center',
                justifyContent: 'center',
                background: 'linear-gradient(135deg, #f5f5f5 0%, #eeeeee 100%)',
                color: 'text.secondary',
                mb: 2,
              }}
            >
              <MapIcon sx={{ fontSize: 64 }} />
              <Typography variant="body2" sx={{ mt: 1 }}>
                Map View
              </Typography>
              <Typography variant="caption">
                {location.latitude.toFixed(4)}, {location.longitude.toFixed(4)}
              </Typography>
            </Box>

            <Button
              href={getGoogleMapsLink()}
              target="_blank"
              rel="noopener noreferrer"
              variant="outlined"
              color="primary"
              size="small"
              fullWidth
              startIcon={<OpenInNewIcon />}
            >
              View in Google Maps
            </Button>
          </CardContent>
        </Card>
      </Popover>
    </>
  )
}

export default LocationPopover

// apps/farmbase/src/farmbase/static/farmbase/src/farm/LocationPopover.vue
<template>
  <v-menu
    v-model="showPopover"
    :close-on-content-click="false"
    location="bottom"
    origin="auto"
    max-width="400"
  >
    <template #activator="{ props }">
      <v-btn
        v-bind="props"
        variant="text"
        color="primary"
        size="small"
        class="text-none"
      >
        <v-icon start>mdi-map-marker</v-icon>
        {{ formatLocation(location) }}
      </v-btn>
    </template>

    <v-card class="pa-4" min-width="350">
      <v-card-title class="text-h6 pb-2">
        <v-icon start>mdi-map-marker</v-icon>
        {{ farmName }} Location
      </v-card-title>
      
      <v-card-text>
        <div class="mb-3">
          <div class="text-caption text-grey">Coordinates</div>
          <div class="text-body-2">
            <strong>Latitude:</strong> {{ location.latitude.toFixed(6) }}<br>
            <strong>Longitude:</strong> {{ location.longitude.toFixed(6) }}
          </div>
        </div>
        
        <!-- Simple map placeholder - in a real app you'd use a proper map component -->
        <div class="map-container">
          <div class="map-placeholder">
            <v-icon size="64" color="primary">mdi-map</v-icon>
            <div class="text-body-2 mt-2">Map View</div>
            <div class="text-caption text-grey">
              {{ location.latitude.toFixed(4) }}, {{ location.longitude.toFixed(4) }}
            </div>
          </div>
        </div>
        
        <div class="mt-3">
          <v-btn
            :href="getGoogleMapsLink()"
            target="_blank"
            color="primary"
            variant="outlined"
            size="small"
            block
          >
            <v-icon start>mdi-open-in-new</v-icon>
            View in Google Maps
          </v-btn>
        </div>
      </v-card-text>
      
      <v-card-actions>
        <v-spacer />
        <v-btn @click="showPopover = false" color="primary">Close</v-btn>
      </v-card-actions>
    </v-card>
  </v-menu>
</template>

<script>
export default {
  name: "LocationPopover",
  props: {
    location: {
      type: Object,
      required: true,
      validator: (value) => {
        return value && typeof value.latitude === 'number' && typeof value.longitude === 'number'
      }
    },
    farmName: {
      type: String,
      default: "Farm"
    }
  },
  data() {
    return {
      showPopover: false,
    }
  },
  methods: {
    formatLocation(location) {
      return `${location.latitude.toFixed(4)}, ${location.longitude.toFixed(4)}`
    },
    getGoogleMapsLink() {
      return `https://www.google.com/maps?q=${this.location.latitude},${this.location.longitude}`
    }
  }
}
</script>

<style scoped>
.map-container {
  height: 150px;
  border: 1px solid #e0e0e0;
  border-radius: 4px;
  overflow: hidden;
}

.map-placeholder {
  height: 100%;
  display: flex;
  flex-direction: column;
  align-items: center;
  justify-content: center;
  background: linear-gradient(135deg, #f5f5f5 0%, #eeeeee 100%);
  color: #666;
}
</style>
