// static/farmbase_react/src/farm/LocationChip.tsx
import React from 'react'
import { Chip } from '@mui/material'
import { LocationOn as LocationIcon } from '@mui/icons-material'

interface Location {
  latitude: number
  longitude: number
  address?: string
}

interface LocationChipProps {
  location: Location
}

const LocationChip: React.FC<LocationChipProps> = ({ location }) => {
  const formatLocation = (loc: Location): string => {
    if (loc.address) {
      return loc.address
    }
    return `${loc.latitude.toFixed(4)}, ${loc.longitude.toFixed(4)}`
  }

  const handleClick = () => {
    const mapsUrl = `https://www.google.com/maps?q=${location.latitude},${location.longitude}`
    window.open(mapsUrl, '_blank', 'noopener,noreferrer')
  }

  return (
    <Chip
      icon={<LocationIcon />}
      label={formatLocation(location)}
      variant="outlined"
      size="small"
      onClick={handleClick}
      sx={{ cursor: 'pointer' }}
    />
  )
}

export default LocationChip

// apps/farmbase/src/farmbase/static/farmbase/src/farm/LocationChip.vue
<template>
  <v-chip
    color="primary"
    variant="tonal"
    size="small"
    @click="openMaps"
    class="location-chip"
  >
    <v-icon start>mdi-map-marker</v-icon>
    {{ formatLocation(location) }}
  </v-chip>
</template>

<script>
export default {
  name: "LocationChip",
  props: {
    location: {
      type: Object,
      required: true,
      validator: (value) => {
        return value && typeof value.latitude === 'number' && typeof value.longitude === 'number'
      }
    }
  },
  methods: {
    formatLocation(location) {
      return `${location.latitude.toFixed(4)}, ${location.longitude.toFixed(4)}`
    },
    openMaps() {
      const url = `https://www.google.com/maps?q=${this.location.latitude},${this.location.longitude}`
      window.open(url, '_blank')
    }
  }
}
</script>

<style scoped>
.location-chip {
  cursor: pointer;
}

.location-chip:hover {
  opacity: 0.8;
}
</style>
