// apps/farmbase/src/farmbase/static/farmbase_react/src/farm/NotesDrawer.tsx
import React from 'react'
import {
  Drawer,
  Card,
  CardContent,
  Typography,
  Box,
  IconButton,
  CircularProgress,
  Chip,
  Divider,
} from '@mui/material'
import {
  Close as CloseIcon,
  StickyNote2 as NoteIcon,
  EventBusy as NoteOffIcon,
} from '@mui/icons-material'
import { useParams } from 'react-router-dom'
import {useFarmStore} from '@/stores/farmStore'
import type { Note } from '@/api/farm'
import LocationChip from './LocationChip'

const NotesDrawer: React.FC = () => {
  const { organization = 'default' } = useParams()
  const { 
    dialogs, 
    selected, 
    notes, 
    closeNotes 
  } = useFarmStore()

  const getImageUrl = (imagePath: string): string => {
    // If the image path is already a full URL, return it as is
    if (imagePath.startsWith('http://') || imagePath.startsWith('https://')) {
      return imagePath
    }
    
    // If it's a relative path, assume it's relative to the API base
    if (imagePath.startsWith('/')) {
      return `file://${imagePath}`
    }
    
    // For paths without leading slash, prepend with standard path
    return `/api/v1/${organization}/files/${imagePath}`
  }

  const handleImageError = (error: any) => {
    console.warn('Failed to load image:', error)
  }

  return (
    <Drawer
      anchor="right"
      open={dialogs.showNotes}
      onClose={closeNotes}
      PaperProps={{
        sx: { width: 600 }
      }}
    >
      <Card sx={{ height: '100%', borderRadius: 0 }}>
        <CardContent>
          {/* Header */}
          <Box sx={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', mb: 2 }}>
            <Typography variant="h6" sx={{ display: 'flex', alignItems: 'center', gap: 1 }}>
              <NoteIcon />
              Farm Notes
            </Typography>
            <IconButton onClick={closeNotes}>
              <CloseIcon />
            </IconButton>
          </Box>

          <Divider sx={{ mb: 2 }} />

          {/* Farm name */}
          {selected?.farm_name && (
            <Typography variant="subtitle1" color="text.secondary" sx={{ mb: 3 }}>
              {selected.farm_name}
            </Typography>
          )}

          {/* Loading state */}
          {notes.loading && (
            <Box sx={{ display: 'flex', flexDirection: 'column', alignItems: 'center', py: 4 }}>
              <CircularProgress />
              <Typography variant="body2" sx={{ mt: 2 }}>
                Loading notes...
              </Typography>
            </Box>
          )}

          {/* Notes content */}
          {!notes.loading && (
            <Box sx={{ maxHeight: '70vh', overflowY: 'auto' }}>
              {notes.items.length === 0 ? (
                <Box sx={{ textAlign: 'center', py: 8, color: 'text.secondary' }}>
                  <NoteOffIcon sx={{ fontSize: 64, color: 'text.disabled', mb: 2 }} />
                  <Typography variant="body1">
                    No notes found for this farm
                  </Typography>
                </Box>
              ) : (
                <Box sx={{ pb: 2 }}>
                  {notes.items.map((note: Note) => (
                    <Card key={note.id} variant="outlined" sx={{ mb: 2 }}>
                      <CardContent>
                        {/* Note content */}
                        <Typography
                          variant="body2"
                          sx={{
                            lineHeight: 1.5,
                            whiteSpace: 'pre-wrap',
                            wordWrap: 'break-word',
                            mb: 2,
                          }}
                        >
                          {note.content}
                        </Typography>

                        {/* Tags - if the note has tags */}
                        {(note as any).tags && (
                          <Box sx={{ mb: 2 }}>
                            <Box sx={{ display: 'flex', flexWrap: 'wrap', gap: 0.5 }}>
                              {(note as any).tags.split(',').map((tag: string, index: number) => (
                                <Chip
                                  key={index}
                                  label={tag.trim()}
                                  size="small"
                                  color="primary"
                                  variant="outlined"
                                />
                              ))}
                            </Box>
                          </Box>
                        )}

                        {/* Location - if the note has location */}
                        {(note as any).location && (
                          <Box sx={{ mb: 2 }}>
                            <Typography variant="caption" color="text.secondary" sx={{ mb: 1, display: 'block' }}>
                              Location
                            </Typography>
                            <LocationChip location={(note as any).location} />
                          </Box>
                        )}

                        {/* Image - if the note has an image */}
                        {(note as any).image_path && (
                          <Box sx={{ mb: 2 }}>
                            <Typography variant="caption" color="text.secondary" sx={{ mb: 1, display: 'block' }}>
                              Attached Image
                            </Typography>
                            <Box
                              component="img"
                              src={getImageUrl((note as any).image_path)}
                              alt={`Image for note ${note.id}`}
                              onError={handleImageError}
                              sx={{
                                maxHeight: 300,
                                maxWidth: '100%',
                                borderRadius: 1,
                                display: 'block',
                              }}
                              onLoad={() => {
                                // Handle successful load if needed
                              }}
                              style={{
                                objectFit: 'contain',
                              }}
                            />
                          </Box>
                        )}

                        {/* Note metadata */}
                        <Box sx={{ display: 'flex', justifyContent: 'flex-end', pt: 1 }}>
                          <Typography variant="caption" color="text.secondary">
                            Note ID: {note.id}
                          </Typography>
                        </Box>
                      </CardContent>
                    </Card>
                  ))}

                  {/* Show total count if there are more notes */}
                  {notes.total !== null && notes.total > notes.items.length && (
                    <Box sx={{ textAlign: 'center', mt: 2 }}>
                      <Typography variant="caption" color="text.secondary">
                        Showing {notes.items.length} of {notes.total} notes
                      </Typography>
                    </Box>
                  )}
                </Box>
              )}
            </Box>
          )}
        </CardContent>
      </Card>
    </Drawer>
  )
}

export default NotesDrawer

// apps/farmbase/src/farmbase/static/farmbase/src/farm/NotesDrawer.vue
<template>
  <v-navigation-drawer
    v-model="showDialog"
    location="right"
    temporary
    width="600"
    class="notes-drawer"
  >
    <v-card flat>
      <v-card-title class="d-flex align-center justify-space-between">
        <span>
          <v-icon start>mdi-note-text</v-icon>
          Farm Notes
        </span>
        <v-btn icon variant="text" @click="closeNotes">
          <v-icon>mdi-close</v-icon>
        </v-btn>
      </v-card-title>
      
      <v-divider />
      
      <v-card-subtitle v-if="selected.farm_name" class="py-2">
        {{ selected.farm_name }}
      </v-card-subtitle>
      
      <v-card-text v-if="notesLoading" class="text-center">
        <v-progress-circular indeterminate />
        <div class="mt-2">Loading notes...</div>
      </v-card-text>
      
      <v-card-text v-else class="notes-content">
        <div v-if="notes.items.length === 0" class="text-center text-grey py-8">
          <v-icon size="64" color="grey-lighten-1">mdi-note-off</v-icon>
          <div class="mt-2">No notes found for this farm</div>
        </div>
        
        <div v-else class="notes-list">
          <v-card
            v-for="note in notes.items"
            :key="note.id"
            variant="outlined"
            class="mb-4"
          >
            <v-card-text>
              <div class="note-content">
                {{ note.note_text }}
              </div>
              
              <div v-if="note.tags" class="mt-3">
                <v-chip-group>
                  <v-chip
                    v-for="tag in note.tags.split(',')"
                    :key="tag.trim()"
                    size="small"
                    color="primary"
                    variant="tonal"
                  >
                    {{ tag.trim() }}
                  </v-chip>
                </v-chip-group>
              </div>
              
              <div v-if="note.location" class="mt-3">
                <div class="text-caption text-grey mb-1">Location</div>
                <location-chip :location="note.location" />
              </div>
              
              <div v-if="note.image_path" class="mt-3">
                <div class="text-caption text-grey mb-2">Attached Image</div>
                <v-img
                  :src="getImageUrl(note.image_path)"
                  :alt="`Image for note ${note.id}`"
                  max-height="300"
                  max-width="100%"
                  class="rounded"
                  @error="handleImageError"
                >
                  <template #placeholder>
                    <div class="d-flex align-center justify-center fill-height">
                      <v-progress-circular indeterminate />
                    </div>
                  </template>
                  <template #error>
                    <div class="d-flex align-center justify-center fill-height bg-grey-lighten-4">
                      <div class="text-center">
                        <v-icon size="48" color="grey">mdi-image-broken</v-icon>
                        <div class="text-caption">Failed to load image</div>
                      </div>
                    </div>
                  </template>
                </v-img>
              </div>
            </v-card-text>
            
            <v-card-actions class="pt-0">
              <v-spacer />
              <div class="text-caption text-grey">
                Note ID: {{ note.id }}
              </div>
            </v-card-actions>
          </v-card>
        </div>
        
        <div v-if="notes.total > notes.items.length" class="text-center mt-4">
          <div class="text-caption text-grey">
            Showing {{ notes.items.length }} of {{ notes.total }} notes
          </div>
        </div>
      </v-card-text>
    </v-card>
  </v-navigation-drawer>
</template>

<script>
import { mapFields } from "vuex-map-fields"
import { mapActions } from "vuex"
import LocationChip from "./LocationChip.vue"

export default {
  name: "NotesDrawer",
  components: { LocationChip },
  
  computed: {
    ...mapFields("farm", [
      "dialogs.showNotes",
      "selected",
      "notes",
      "notes.loading",
    ]),
    showDialog: {
      get() {
        return this.showNotes
      },
      set(value) {
        if (!value) {
          this.closeNotes()
        }
      }
    },
    notesLoading() {
      return this.loading
    }
  },
  
  methods: {
    ...mapActions("farm", ["closeNotes"]),
    getImageUrl(imagePath) {
      // If the image path is already a full URL, return it as is
      if (imagePath.startsWith('http://') || imagePath.startsWith('https://')) {
        return imagePath
      }
      console.log(`file://${imagePath}`)
      // If it's a relative path, assume it's relative to the API base
      // This will work with the farmbase API structure
      if (imagePath.startsWith('/')) {
        return `file://${imagePath}`
      }
      
      // For paths without leading slash, prepend with standard path
      return `/api/v1/${this.$route.params.organization || 'default'}/files/${imagePath}`
    },
    handleImageError(error) {
      console.warn('Failed to load image:', error)
    }
  }
}
</script>

<style scoped>
.notes-drawer {
  z-index: 1000;
}

.notes-content {
  max-height: 70vh;
  overflow-y: auto;
}

.note-content {
  line-height: 1.5;
  white-space: pre-wrap;
  word-wrap: break-word;
}

.notes-list {
  padding-bottom: 20px;
}
</style>
